Repository puppetlabs/rspec-puppet, pull requests merged in 2023-10, with the labels that each got.

#72 (CAT-836) - Bump Jquery to 3.7.1 & Bootstrap 5.3.2
  .rubocop.yml
  .rubocop_todo.yml
  README.md
  docs/_layouts/base.html
  docs/_layouts/cards.html
  docs/assets/plugins/bootstrap/css/bootstrap-theme.css
  docs/assets/plugins/bootstrap/css/bootstrap-theme.css.map
  docs/assets/plugins/bootstrap/css/bootstrap-theme.min.css
  docs/assets/plugins/bootstrap/css/bootstrap-theme.min.css.map
  docs/assets/plugins/bootstrap/css/bootstrap.css
  docs/assets/plugins/bootstrap/css/bootstrap.css.map
  docs/assets/plugins/bootstrap/css/bootstrap.min.css
  docs/assets/plugins/bootstrap/css/bootstrap.min.css.map
  docs/assets/plugins/bootstrap/js/bootstrap.js
  docs/assets/plugins/bootstrap/js/bootstrap.min.js
  docs/assets/plugins/jquery-1.12.3.min.js
  docs/assets/plugins/jquery-3.7.1.min.js
  docs/assets/plugins/jquery-scrollTo/demo/css/style.css
  docs/assets/plugins/jquery-scrollTo/demo/css/style.old.css
  docs/assets/plugins/jquery-scrollTo/demo/index.html
  docs/assets/plugins/jquery-scrollTo/demo/index.old.html
  docs/assets/plugins/lightbox/examples/index.html
  docs/assets/plugins/lightbox/examples/remote/page1.html
  docs/assets/plugins/lightbox/examples/remote/page2.html
  docs/assets/plugins/lightbox/examples/remote/readme.md
  docs/index.html
Labels: maintenance

#67 Drop RSpec 2 & Ruby 1 compatiblity
  Rakefile
  lib/rspec-puppet/monkey_patches.rb
  lib/rspec-puppet/support.rb
  rspec-puppet.gemspec
  spec/classes/test_windows_spec.rb
  spec/spec_helper.rb
  spec/spec_helper_unit.rb
  spec/unit/matchers/count_generic_spec.rb
  spec/unit/matchers/include_class_spec.rb
  spec/unit/matchers/run_spec.rb
Labels: community, backwards-incompatible

#73 (CAT-1226) - Remove Compatibility for Puppet 7.11 and below
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .rubocop_todo.yml
  README.md
  docs/documentation/configuration/index.md
  docs/documentation/coverage/index.md
  docs/documentation/setup/index.md
  lib/rspec-puppet.rb
  lib/rspec-puppet/adapters.rb
  lib/rspec-puppet/example/function_example_group.rb
  lib/rspec-puppet/monkey_patches.rb
  lib/rspec-puppet/sensitive.rb
  lib/rspec-puppet/setup.rb
  lib/rspec-puppet/spec_helper.rb
  lib/rspec-puppet/support.rb
  spec/classes/array_spec.rb
  spec/classes/default_spec.rb
  spec/classes/deferred_spec.rb
  spec/classes/facts_spec.rb
  spec/classes/hash_spec.rb
  spec/classes/hiera_integration_spec.rb
  spec/classes/map_reduce_spec.rb
  spec/classes/node_params_spec.rb
  spec/classes/relationships__type_with_auto_spec.rb
  spec/classes/server_facts_spec.rb
  spec/classes/test_api_spec.rb
  spec/classes/test_basic_spec.rb
  spec/classes/test_registry_spec.rb
  spec/classes/test_sensitive_spec.rb
  spec/classes/trusted_external_data_spec.rb
  spec/classes/trusted_facts_spec.rb
  spec/classes/type_mismatch_spec.rb
  spec/classes/undef_spec.rb
  spec/defines/undef_def_spec.rb
  spec/functions/facts_lookup_spec.rb
  spec/functions/lambda_function_spec.rb
  spec/functions/nil_function_spec.rb
  spec/functions/split_spec.rb
  spec/functions/test_function_spec.rb
  spec/functions/test_hiera_function_spec.rb
  spec/functions/trusted_facts_lookup_spec.rb
  spec/hosts/environment_spec.rb
  spec/spec_helper.rb
  spec/support_spec.rb
  spec/type_aliases/onlyarray_spec.rb
  spec/type_aliases/onlyhash_spec.rb
  spec/type_aliases/shape_spec.rb
  spec/unit/adapters_spec.rb
  spec/unit/example/function_example_group_spec.rb
  spec/unit/matchers/allow_value_spec.rb
  spec/unit/matchers/compile_spec.rb
  spec/unit/monkey_patches_spec.rb
  spec/unit/sensitive_spec.rb
Labels: backwards-incompatible, hacktoberfest

#75 (CAT-1224) - Bring README up-to-date
  README.md
Labels: maintenance, hacktoberfest

#77 (maint) - Add gem description pointing to new gem
  rspec-puppet.gemspec
Labels: maintenance

#79 (maint) - remove irrelevant readme sections
  README.md
Labels: maintenance

#80 (maint) - Removed soon-to-be deprecated RSpec/FilePath cops
  .rubocop.yml
  .rubocop_todo.yml
Labels: maintenance

#76 (CAT-1235) - Rename to puppetlabs-rspec-puppet
  rspec-puppet.gemspec
Labels: backwards-incompatible

#82 (CAT-1529) Update README.md LICENSE
  README.md
Labels: maintenance
