Repository puppetlabs/rspec-puppet, pull requests merged in 2023-07, with the labels that each got.

#60 (maint) : Fixing cops
  lib/rspec-puppet/support.rb
Labels: maintenance

#45 doc : add information about sensitive helper
  docs/_includes/catalogue_matchers.md
Labels: maintenance

#54 Remove puppet applications support
  README.md
  Rakefile
  docs/documentation/applications/index.md
  docs/documentation/index.md
  lib/rspec-puppet/example.rb
  lib/rspec-puppet/example/application_example_group.rb
  lib/rspec-puppet/support.rb
  spec/fixtures/modules/orch_app/manifests/db.pp
  spec/fixtures/modules/orch_app/manifests/init.pp
Labels: community, MayTheSourceBeWithYou

#61 Avoid hardcoding ipaddress6 default
  lib/rspec-puppet/support.rb
Labels: community

#62 pdksync - (CONT-1219) - fail ci for puppetlabs members if no label
  .github/workflows/labeller.yml
Labels: maintenance

#63 (maint) - fix rubocop
  lib/rspec-puppet/matchers/dynamic_matchers.rb
Labels: maintenance
