Repository puppetlabs/rspec-puppet, pull requests merged in 2024-02, with the labels that each got.

#105 pdksync - (CAT-770) - Update mend to run on pull_request_target
  .github/workflows/mend.yml
Labels: maintenance

#106 Update CODEOWNERS
  CODEOWNERS
Labels: maintenance

#108 (bug) - Add license file to built gem
  rspec-puppet.gemspec
Labels: bugfix

#96 dependabot: check for github actions and bundler
  .github/dependabot.yml
Labels: community
